### ISSUE TITLE
Thông tin Owner tại mục Installations bị chuyển hướng sai ID khi tra cứu Owner/Contact

### ISSUE THREAD

**Issue by huydv398** [hocchudong/netbox-software-version-manager#11]
Khi thực hiện tra cứu Owner được gắn tại Installations:

Thực hiện Click vào contact muốn tra cứu thông tin
![image](https://github.com/user-attachments/assets/c130f49b-ba25-4697-bc48-ac0b0f501c85)

Trang chuyển hướng đến ID Contact bị sai dẫn đến Contacts không khớp khi tra cứu

![image](https://github.com/user-attachments/assets/286337eb-2cdc-4b1b-84ca-6b8b08fac693)

**Comment by huytm** [comment]
Fixed
